# Generated by Django 5.0.2 on 2024-03-11 13:00

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Property Name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('province', models.CharField(max_length=200, verbose_name='Province')),
                ('listing_type', models.CharField(max_length=20, verbose_name='Listing Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('parking', models.PositiveIntegerField(default=0, verbose_name='Parking Space')),
                ('bathroom', models.PositiveIntegerField(default=0, verbose_name='Bathroom')),
                ('bedroom', models.PositiveIntegerField(default=0, verbose_name='Bedroom')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacenest.property')),
            ],
        ),
    ]
