# Generated by Django 5.0.2 on 2024-03-11 16:54

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacenest', '0004_alter_favourite_id_alter_property_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], max_length=20, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.CharField(choices=[('koshi', 'Koshi Province'), ('madhesh', 'Madhesh Province'), ('bagmati', 'Bagmati Province'), ('gandaki', 'Gandaki Province'), ('lumbini', 'Lumbini Province'), ('karnali', 'Karnali Province'), ('sudurpashchim', 'Sudurpashchim Province')], max_length=200, verbose_name='Province'),
        ),
    ]
