# Generated by Django 5.0.2 on 2024-03-20 15:46

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacenest', '0017_alter_favourite_id_alter_favourite_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='content',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='title',
        ),
        migrations.AddField(
            model_name='mailbox',
            name='date',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='message',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='phone',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
